### ISSUE TITLE
Is this repo been excluded from hacktoberfest?

### ISSUE THREAD

**Issue by ItsRoy69** [MSCKIIT/Small-Projects#315]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mk1107** [comment]
![image](https://user-images.githubusercontent.com/55909616/136221085-eacddf57-9968-4283-99b4-fc82fb739916.png)
I am also getting this error

**Comment by m1ga** [comment]
thats a different repo by the name but yes: sounds like a repo made just for Hacktoberfest to get free swag :smile:

**Comment by mk1107** [comment]
But here I added many things like the flutter app

**Comment by moazfarrukh** [comment]
![image](https://user-images.githubusercontent.com/21291203/136239966-a8cc87c1-9dfe-4f34-bf57-2c2fef834e9a.png)
i am also getting this i am sure this is the same repo . As i am being shown as a contributor here

**Comment by m1ga** [comment]
> But here I added many things like the flutter app

@mk1107 which is good and perhaps it helps people. But it just doesn't count as a contribution to hacktoberfest because repos with just list of random projects (like "add your project" or "add a search in a programming language") popping up all over github at the moment. Those are the rules this year. 
Just find a different project that is not just a list of stuff or that was created 5 days ago with a preset ("here is my portfolio, add something"). Check the hacktoberfest discord, twitter or curated lists like https://hacktoberfestswaglist.com/ for projects.

And again: nothing wrong with contributing to this repo! If your contribution serves a purpose and helps others: well done!
Hope you would have done it even without Hacktoberfest. But since people are complaining that their PRs are excluded is really sound that they just did it for the swag :wink:

**Comment by m1ga** [comment]
> okay I just removed errors from their code but it's okay but deep down i feel sad

So the person who uses that code later on see less errors, nice :+1: So you should be happy. 
Just do more of that in different projects and you should be fine.
